### PR TITLE
Enable full access to devices

### LINKED ISSUE #35: Error when addon trying to access/dev/i2c-1
# Problem/Motivation
I have RPi-OS and hassio supervised installed on my RPi4. When I try to run addon-mqtt-io with a BME280 sensor connected locally via GPIO I2C, I get below error:

> PermissionError: [Errno 1] Operation not permitted: '/dev/i2c-1'

The same problem occurs on RPi3b running on the latest haos-9.3 system. I tried to diagnose the problem, the conclusions are as below.

## Actual behavior

Addon Logs:
```bash
  File "/usr/lib/python3.10/site-packages/mqtt_io/server.py", line 128, in _init_module
    return module_class(module_config)
  File "/usr/lib/python3.10/site-packages/mqtt_io/modules/sensor/__init__.py", line 22, in __init__
    self.setup_module()
  File "/usr/lib/python3.10/site-packages/mqtt_io/modules/sensor/bme280.py", line 38, in setup_module
    self.bus = SMBus(self.config["i2c_bus_num"])
  File "/usr/lib/python3.10/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/usr/lib/python3.10/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
PermissionError: [Errno 1] Operation not permitted: '/dev/i2c-1'
[11:29:09] WARNING: MQTT IO crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[11:29:10] INFO: MQTT IO stopped
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
[mqtt-io_log.txt](https://github.com/hassio-addons/addon-mqtt-io/files/9952633/mqtt-io_log.txt)

## Steps to reproduce

The plugin configuration is as follows  **/config/mqtt-io/config.yml**:
```bash
mqtt:
  host: core-mosquitto
  user: homeassistant
  password: [hidden]
  topic_prefix: mqtt-io
sensor_modules:
  # BME280 on I2C bus
  - name: bme_sensor
    module: bme280
    i2c_bus_num: 1
    chip_addr: 0x76
sensor_inputs:
  - name: sen1_temperature
    module: bme_sensor
```

Sensor BME280 connected to i2c-1 interface GPIO RPi4.

### 1. Read GPIO i2c from RPI4 host:
Check the operation of the BME280 sensor directly from the host:
```bash
[root@home /]# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
```
```bash
[root@home /home/awitt/temp]# read_bme280 --i2c-address 0x76
1002.46 hPa
  49.42 %
  24.11 C

```
### 2. Read GPIO i2c from container addon-mqtt-io
Then I run the same commands in the mqtt-io container running in HA. I'm starting the add-on with minimal configuration **/config/mqtt-io/config.yml**

```bash
mqtt:
  host: core-mosquitto
  user: homeassistant
  password: [hidden]
  topic_prefix: mqtt-io
```
then from the host CLI enter the mqtt-io container:
```bash
[root@home /]# docker exec -it addon_a0d7b954_mqtt-io bash
```
then in the container:
```bash
apk add --no-cache i2c-tools && i2cdetect -y 1
```
as a result of the command, I get the response:
```bash
a0d7b954-mqtt-io:~# apk add --no-cache i2c-tools && i2cdetect -y 1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/1) Installing i2c-tools (4.3-r1)
Executing busybox-1.35.0-r17.trigger
OK: 89 MiB in 54 packages
Error: Could not open file `/dev/i2c-1': Operation not permitted
a0d7b954-mqtt-io:~#
```
[mqtt-io_docker_inspect.txt](https://github.com/hassio-addons/addon-mqtt-io/files/9952643/mqtt-io_docker_inspect.txt)

### 3. Read GPIO i2c from new alpine container
I'm running the alpine: latest container with permissions:
SYS_RAWIO
/dev/mem
/dev/gpiomem

```bash
[root@home /]# docker run -it --rm --cap-add SYS_RAWIO --device /dev/mem --device /dev/gpiomem alpine:latest sh
```
and run i2c test:
```bash
[root@home /]# docker run -it --rm --cap-add SYS_RAWIO --device /dev/mem --device /dev/gpiomem alpine:latest sh
/ # apk add --no-cache i2c-tools && i2cdetect -y 1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/1) Installing i2c-tools (4.3-r1)
Executing busybox-1.35.0-r17.trigger
OK: 6 MiB in 15 packages
Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1': No such file or directory
/ #
```

### 4. Read GPIO i2c from new alpine container (/dev/i2c-1)
I'm running the alpine: latest container with permissions:
/dev/i2c-1

```bash
[root@home /]#  docker run -it --rm --device /dev/i2c-1 alpine:latest sh
/ # apk add --no-cache i2c-tools && i2cdetect -y 1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/1) Installing i2c-tools (4.3-r1)
Executing busybox-1.35.0-r17.trigger
OK: 6 MiB in 15 packages
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
/ #

```
## System Info
```bash
[root@home /]# uname -a
Linux home 5.15.74-v8+ #1595 SMP PREEMPT Wed Oct 26 11:07:24 BST 2022 aarch64 GNU/Linux

[root@home /]# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
 Add-on version: 0.1.3
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.2

## Questions
1. How do I get the plug to work? In the docker container called with the parameters `--cap-add SYS_RAWIO --device / dev / mem --device / dev / gpiomem` it wont work.

2. Changing the parameters `SUBSYSTEM=="i2c-dev", GROUP="i2c", MODE="0666"` oraz `SUBSYSTEM=="gpio", GROUP="gpio", MODE="0666"` it doesn't help

3. The problem seems to be resolved after mapping `/dev/i2c-1`. So, should this parameter be added to the plugin configuration?

### PR DESCRIPTION
**Pull request by frenck**
# Proposed Changes

A possible solution for #35.
This will highly degrade the security rating for this add-on, but it will provide the max access to hardware an add-on can possibly get in the Home Assistant ecosystem.

## Related Issues

needs #37
closes #35

### CODE REVIEW

**Comment by thecode** [comment]
So this doesn't work, however mapping `/dev`:
```
devices:
  - /dev
```
and disabling protection mode, maps everything under `/dev` to the container and is working, I don't know if this is an acceptable solution, but it should work for everything `mqtt-io` supports as it access devices under `/dev`

**Comment by frenck** [comment]
Some questions/things to explore:
- Does just `full_access` with disabled protection work?
- Does just `/dev` in `devices` (without `full_access`) with disabled protection work?
- Or do we need both the `devices` and `full_access` with disabled protection?

**Comment by thecode** [comment]
> * Does just `full_access` with disabled protection work?

No
> * Does just `/dev` in `devices` (without `full_access`) with disabled protection work?

Yes

> * Or do we need both the `devices` and `full_access` with disabled protection?

No need for `full_access`

**Comment by ysc3839** [comment]
I tested on my device. It works just change devices to /dev, without full_access.

**Comment by thecode** [comment]
> I tested on my device. It works just change devices to /dev, without full_access.

Did you run the addon with protection mode disabled?

**Comment by ysc3839** [comment]
@thecode I didn't add `full_access`, so there's no protection mode option.

**Comment by Bluscream** [comment]
Can we atleast have /dev access so the addon is not 100% useless on RPi?

**Comment by frenck** [comment]
@Bluscream I've marked your comment as off-topic. If you want to provide technical comment on the contents of this PR: Please do, as that is what pull requests reviews are for (but your response wasn't that). This is a PR, and not a general discussion forum. 

Thanks 👍 

../Frenck

**Comment by frenck** [comment]
@Bluscream Correct, which is already written above. So 🤷

**Review by thecode — APPROVED** [review]

**Comment by thecode** [comment]
I can check it later today on a PI, but should be good to merge

**Comment by frenck** [comment]
It won't be more broken :)
Also, if issues occur I'm able to act up on it fast the coming days :)

**Pull request merged**
